name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Set git creds
      run:
        - git config user.email "piet.brauer@mhp.com"
        - git config user.name "Piet Brauer"
    - name: Deploy to GH Pages
      run: npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
