name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy
      run: |
        git config --global user.email "piet.brauer@mhp.com"
        git config --global user.name "Piet Brauer"
        git remote set-url origin https://$GITHUB_ACCESS_TOKEN@github.com/pietbrauer/oso-cd-test.git
        npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
